sudo: required
language: java
install: "./scripts/install.sh"
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
    env:
    - JACOCO_COVERAGE=true
  - os: linux
    jdk: oraclejdk9
  - os: linux
    jdk: oraclejdk9
    env:
    - SNOWFLAKE_AZURE=true
script:
  - "./scripts/run_travis.sh"
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: pPK8xlDKO5l/lGvSym81fVGyfoIBPvPeaUVMZRFqcgVhSO6XHCS0Ktn2t8Y6VgT1MN9njLS5ewQ3uDX/7iZ9a3t3iHFstU6FLAQTxdahn0WLi3T9Dfj7aOpC+JaTUr4eWHZZNHs6635OFfOXEw7XoMIJIZ5jjexuRwnUf+RJ7siN3qbeTozxFHY95VjJKNZZ4ga3GyXeuvpJTVlYJT2JfvJUpMPJQV6cjdVOhAn8LiusNXieKrURdTbemCYgO0+Fe9kUusMKfJPdMEfufcvKnE4jk4XC61J47QCBQl9CRtkGi2uCOepwOlIXXsR3nZtGP9SB/INDkpzlbpx2e2f2sBkFXuM74bbcLfrAAbdgjjhJTI5f0aD+/FC+mQ2AsA97nrlqltbEXsml/rS+vUvCn3N9mmFQuAHVPSx5LNzD0bOmAKNDElIqIrCNXvu/DR+CYvrwosKK+YHcmBmrl5ZlY/WT7Mm2FVENww4P7e8AJrVFQaOVA1rOyMu/9/Vc6NvHHQs3ha/zU6OBtR5v2g5qBxdrDaPh1H0O0N4U6cr3wNett8cT8CbmqRDxvqyl46697kgj3Xzf5V8BJnyiGb8qgJ89IBD6AqxTaFvMpkGhTTKRzYzYnZwsZJ66gMRmLCGIljeObaEx+FR9Kqodr4CCpmYCrI3LK0KWG7pIBdm47Y0=
  - secure: OLKoboHczS6UChxw6A0kzbvAbbKlc1RFUgVSIVJqwLLwaJmL304IQjHYsj72jkRYRL4ItYUx+Ume5D94Kc3TAOos5GtR20/zAa0AdAigx6U/eO2h6VJH4fUqG/0T1xolaHyvMUTbjNKirc4r7Aht6FY1u7YKEPNQCStprDI1QNMbT4mcKW9iImAxKoFXaYgDoZdoef9Lm5tdU2gnwWLQM0cZWHPcXhg2xdTFsLOWyJ+HElwtd91mJvRvjTmgAPj8zHjRaInGpErNMWBGg3nzh9d7xTtcNcLVnKkokS4J5Tw1EkRE3j46EbqZwr+Clk66EMyaqBZxElGULf/blF5r79s+oq2iMSJubElZBq+eyoBzxz/asHqzfPAAElD+CG3AZEOXqJmFbue6IR3vZqBjgp1/IPHUY9+b0gFROV+F4MWwsRPN5fjgxsYzIoJDCtTgZLNlCMzIsepDnKYx/NX4fs2DBndOAkPHezoGX/USK1mfqQYrZsMu5TiEjHReyZbU/PGuq6uWAqxtZo0KqzFfSnuJmjt9jfkDqcQBDTVSVb/GVjHoJEBYhgbLayGZ1y+v0nKNx8o5019vNui3cEtFOvMlSG8uAke17pySLiwPtfOEIkpV+rMkdqlw6r1zoxG6dA99bTRSvN2QkPNMZGYtWkPL+4mf82Al7QhjXPTFcbs=
