handlers = java.util.logging.FileHandler
.level = FINE

java.util.logging.FileHandler.pattern = %t/fat-jar-test.log
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.FileHandler.level = ALL
