package net.snowflake.client.api.connection;

import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import net.snowflake.client.api.exception.SnowflakeSQLException;

/** This interface defines Snowflake specific APIs for Connection */
public interface SnowflakeConnection {
  /**
   * Method to compress data from a stream and upload it at a stage location. The data will be
   * uploaded as one file. No splitting is done in this method.
   *
   * <p>caller is responsible for releasing the inputStream after the method is called.
   *
   * @param stageName stage name: e.g. ~ or table name or stage name
   * @param destPrefix path prefix under which the data should be uploaded on the stage
   * @param inputStream input stream from which the data will be uploaded
   * @param destFileName destination file name to use
   * @param compressData compress data or not before uploading stream
   * @throws SQLException failed to compress and put data from a stream at stage
   */
  void uploadStream(
      String stageName,
      String destPrefix,
      InputStream inputStream,
      String destFileName,
      boolean compressData)
      throws SQLException;

  /**
   * Download file from the given stage and return an input stream
   *
   * @param stageName stage name
   * @param sourceFileName file path in stage
   * @param decompress true if file compressed
   * @return an input stream
   * @throws SnowflakeSQLException if any SQL error occurs.
   */
  InputStream downloadStream(String stageName, String sourceFileName, boolean decompress)
      throws SQLException;

  /**
   * Return unique session ID from current session generated by making connection
   *
   * @return a unique alphanumeric value representing current session ID
   * @throws SQLException if an error occurs
   */
  String getSessionID() throws SQLException;

  /**
   * Create a new instance of a ResultSet object based off query ID. ResultSet will contain results
   * of corresponding query. Used when original ResultSet object is no longer available, such as
   * when original connection has been closed.
   *
   * @param queryID the query ID
   * @return ResultSet based off the query ID
   * @throws SQLException if an error occurs
   */
  ResultSet createResultSet(String queryID) throws SQLException;

  /**
   * Return an array of child query IDs for the given query ID.
   *
   * <p>If the given query ID is for a multiple statements query, it returns an array of its child
   * statements, otherwise, it returns an array to include the given query ID.
   *
   * @param queryID The given query ID
   * @return An array of child query IDs
   * @throws SQLException If the query is running or the corresponding query is FAILED.
   */
  String[] getChildQueryIds(String queryID) throws SQLException;

  /**
   * Get the major version of the Snowflake database.
   *
   * @return database major version
   * @throws SQLException if an error occurs
   */
  int getDatabaseMajorVersion() throws SQLException;

  /**
   * Get the minor version of the Snowflake database.
   *
   * @return database minor version
   * @throws SQLException if an error occurs
   */
  int getDatabaseMinorVersion() throws SQLException;

  /**
   * Get the full version string of the Snowflake database.
   *
   * @return database version string
   * @throws SQLException if an error occurs
   */
  String getDatabaseVersion() throws SQLException;
}
