package net.snowflake.client.api.connection;

import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;

/** This interface defines Snowflake specific APIs for Connection */
public interface SnowflakeConnection {
  /**
   * Upload data from a stream to a Snowflake stage with required parameters only.
   *
   * <p>This is a convenience method that uses default options (compress data, no destination
   * prefix). For advanced configuration, use {@link #uploadStream(String, String, InputStream,
   * UploadStreamConfig)}.
   *
   * <p>The caller is responsible for closing the input stream after upload completes.
   *
   * @param stageName the name of the stage (e.g., "@my_stage")
   * @param destFileName the destination file name on the stage
   * @param inputStream the input stream containing data to upload
   * @throws SQLException if upload fails
   */
  void uploadStream(String stageName, String destFileName, InputStream inputStream)
      throws SQLException;

  /**
   * Upload data from a stream to a Snowflake stage with optional configuration.
   *
   * <p>This method allows customization of upload behavior via {@link UploadStreamConfig}, such as
   * setting a destination prefix or controlling compression.
   *
   * <p>The caller is responsible for closing the input stream after upload completes.
   *
   * @param stageName the name of the stage (e.g., "@my_stage")
   * @param destFileName the destination file name on the stage
   * @param inputStream the input stream containing data to upload
   * @param config optional configuration for upload behavior
   * @throws SQLException if upload fails
   */
  void uploadStream(
      String stageName, String destFileName, InputStream inputStream, UploadStreamConfig config)
      throws SQLException;

  /**
   * Download a file from a Snowflake stage as a stream with required parameters only.
   *
   * <p>This is a convenience method that uses default options (no decompression). For advanced
   * configuration, use {@link #downloadStream(String, String, DownloadStreamConfig)}.
   *
   * <p>The caller is responsible for closing the returned input stream.
   *
   * @param stageName the name of the stage (e.g., "@my_stage")
   * @param sourceFileName the path to the file within the stage
   * @return an input stream containing the file data
   * @throws SQLException if download fails
   */
  InputStream downloadStream(String stageName, String sourceFileName) throws SQLException;

  /**
   * Download a file from a Snowflake stage as a stream with optional configuration.
   *
   * <p>This method allows customization of download behavior via {@link DownloadStreamConfig}, such
   * as automatic decompression.
   *
   * <p>The caller is responsible for closing the returned input stream.
   *
   * @param stageName the name of the stage (e.g., "@my_stage")
   * @param sourceFileName the path to the file within the stage
   * @param config optional configuration for download behavior
   * @return an input stream containing the file data
   * @throws SQLException if download fails
   */
  InputStream downloadStream(String stageName, String sourceFileName, DownloadStreamConfig config)
      throws SQLException;

  /**
   * Return unique session ID from current session generated by making connection
   *
   * @return a unique alphanumeric value representing current session ID
   * @throws SQLException if an error occurs
   */
  String getSessionID() throws SQLException;

  /**
   * Create a new instance of a ResultSet object based off query ID. ResultSet will contain results
   * of corresponding query. Used when original ResultSet object is no longer available, such as
   * when original connection has been closed.
   *
   * @param queryID the query ID
   * @return ResultSet based off the query ID
   * @throws SQLException if an error occurs
   */
  ResultSet createResultSet(String queryID) throws SQLException;

  /**
   * Return an array of child query IDs for the given query ID.
   *
   * <p>If the given query ID is for a multiple statements query, it returns an array of its child
   * statements, otherwise, it returns an array to include the given query ID.
   *
   * @param queryID The given query ID
   * @return An array of child query IDs
   * @throws SQLException If the query is running or the corresponding query is FAILED.
   */
  String[] getChildQueryIds(String queryID) throws SQLException;

  /**
   * Get the major version of the Snowflake database.
   *
   * @return database major version
   * @throws SQLException if an error occurs
   */
  int getDatabaseMajorVersion() throws SQLException;

  /**
   * Get the minor version of the Snowflake database.
   *
   * @return database minor version
   * @throws SQLException if an error occurs
   */
  int getDatabaseMinorVersion() throws SQLException;

  /**
   * Get the full version string of the Snowflake database.
   *
   * @return database version string
   * @throws SQLException if an error occurs
   */
  String getDatabaseVersion() throws SQLException;
}
