name: Check Style

on:
    pull_request:
        branches:
            - master
jobs:
    check-style:
        name: Check Style
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check Style
              shell: bash
              run: mvn clean validate --batch-mode --show-version -P check-style
