name: Check Style

on:
    pull_request:
        branches:
            - master
jobs:
    check-style:
        name: Check Style
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v1
            - name: Check Style
              shell: bash
              run: mvn clean verify --batch-mode --show-version -P check-style
