name: whitesource
on:
  pull_request:
    branches:
      - master
jobs:
  whitesource:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'whitesource-for-github-com[bot]' }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: checkout action
      uses: actions/checkout@v2
      with:
        repository: snowflakedb/whitesource-actions
        token: ${{ secrets.WHITESOURCE_ACTION_TOKEN }}
        path: whitesource-actions

    - name: PR
      uses: ./whitesource-actions/whitesource-pr
      with:
        jira_token: ${{ secrets.JIRA_TOKEN_PUBLIC_REPO }}
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        amend: false # true if you want the commit to be amended with the JIRA number
