
name: whitesource-issue

on:
  issues:
    types: [opened, reopened]

concurrency: whitesource-issue

jobs:
  whitesource:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.user.login == 'whitesource-for-github-com[bot]' }}
    steps:
    - name: checkout action
      uses: actions/checkout@v2
      with:
        repository: snowflakedb/whitesource-actions
        token: ${{ secrets.WHITESOURCE_ACTION_TOKEN }}
        path: whitesource-actions

    - name: Jira Creation
      uses: ./whitesource-actions/whitesource-issue
      with:
        jira_token: ${{ secrets.JIRA_TOKEN_PUBLIC_REPO }}
        gh_token: ${{ secrets.GITHUB_TOKEN }}
